# Generated by Django 2.0.3 on 2018-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Student_name', models.CharField(max_length=30)),
                ('gpa', models.IntegerField(default=0, max_length=30)),
            ],
        ),
    ]
