# Generated by Django 5.2.6 on 2025-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200316_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_taken',
            name='Grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
    ]
