# Generated by Django 5.2.6 on 2025-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_course_taken_grade_alter_student_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=100)),
                ('Actor1Name', models.CharField(max_length=50)),
                ('Actor2Name', models.CharField(blank=True, max_length=50)),
                ('DirectorName', models.CharField(max_length=50)),
                ('MovieGenre', models.CharField(max_length=30)),
                ('ReleaseYear', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Taken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
