# Generated by Django 5.2.6 on 2025-09-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_video_delete_course_taken_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='MovieID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='ReleaseYear',
            field=models.IntegerField(),
        ),
    ]
